spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    data-username: admin
    data-password: password
    url: jdbc:h2:./db/hosDB

