spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: admin
    password: password
    url: jdbc:h2:./db/hosDB


